# Generated by Django 2.2.10 on 2020-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='token_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
